/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/porsche.glb --typescript 
Author: n.brizitskaya (https://sketchfab.com/n.brizitskaya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porsche-911-with-interior-877b1bc1739f4a2bb65d62fd7ffd9f75
Title: Porsche 911 with interior
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/porsche.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.windows_main_windows_0.geometry} material={materials.windows} />
          <mesh geometry={nodes.windows_main_windows_edge_0.geometry} material={materials.windows_edge} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.body_circles_body_main_0.geometry} material={materials.body_main} />
          <mesh geometry={nodes.body_circles_invisible_all_0.geometry} material={materials.invisible_all} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.wheel_rim_rim_black_0.geometry} material={materials.rim_black} />
          <mesh geometry={nodes.wheel_rim_rim_chrome_0.geometry} material={materials.rim_chrome} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.headlights_plastics_hedlights_grid_0.geometry} material={materials.hedlights_grid} />
          <mesh geometry={nodes.headlights_plastics_headlights_plastic_ring_0.geometry} material={materials.headlights_plastic_ring} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.leather_all_leather_int_0.geometry} material={materials.leather_int} />
          <mesh geometry={nodes.leather_all_leather_seam_0.geometry} material={materials.leather_seam} />
          <mesh geometry={nodes.leather_all_leather_perforated_0.geometry} material={materials.leather_perforated} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.plastic_all_bl_pl_M_int_0.geometry} material={materials.bl_pl_M_int} />
          <mesh geometry={nodes.plastic_all_bl_pl_M_int_0_1.geometry} material={materials.bl_pl_M_int} />
          <mesh geometry={nodes.plastic_all_interior_grid_0.geometry} material={materials.interior_grid} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.mirror_door_1_Mirror_0.geometry} material={materials.Mirror} />
          <mesh geometry={nodes.reisin__door_1_reisin_0.geometry} material={materials.reisin} />
          <mesh geometry={nodes.plastic_exterior_door_1_bl_pl_M_ext_0.geometry} material={materials.bl_pl_M_ext} />
          <mesh geometry={nodes.carbon__door_1_carbon_int_0.geometry} material={materials.carbon_int} />
          <mesh geometry={nodes.dynamics_door_1_dynamics_0.geometry} material={materials.dynamics} />
          <mesh geometry={nodes.screw_door_1_black_metal_0.geometry} material={materials.black_metal} />
          <mesh geometry={nodes.logo_door_1_LOGO1_0.geometry} material={materials.LOGO1} />
          <mesh geometry={nodes.reflector_door_1_reflectors_0.geometry} material={materials.reflectors} />
          <mesh geometry={nodes.leather_door_1_leather_int_0.geometry} material={materials.leather_int} />
          <mesh geometry={nodes.leather_door_1_leather_seam_0.geometry} material={materials.leather_seam} />
          <mesh geometry={nodes.body__door_1_body_main_0.geometry} material={materials.body_main} />
          <mesh geometry={nodes.window_door_1_windows_0.geometry} material={materials.windows} />
          <mesh geometry={nodes.window_door_1_windows_edge_0.geometry} material={materials.windows_edge} />
          <mesh geometry={nodes.plastic_door_1_bl_pl_M_int_0.geometry} material={materials.bl_pl_M_int} />
          <mesh geometry={nodes.mirror_cover_door_1_monitor_0.geometry} material={materials.monitor} />
          <mesh geometry={nodes.chrome_door_1_chrom_int_0.geometry} material={materials.chrom_int} />
          <mesh geometry={nodes.leathplast_door_1_pl_leather_int_0.geometry} material={materials.pl_leather_int} />
        </group>
        <group position={[-106.399, 0, 90.735]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]}>
          <mesh geometry={nodes.mirror_door_2_Mirror_0.geometry} material={materials.Mirror} />
          <mesh geometry={nodes.body_door_2_body_main_0.geometry} material={materials.body_main} />
          <mesh geometry={nodes.plastic_door_2_bl_pl_M_int_0.geometry} material={materials.bl_pl_M_int} />
          <mesh geometry={nodes.leath_plast_door_2_pl_leather_int_0.geometry} material={materials.pl_leather_int} />
          <mesh geometry={nodes.chrome__door_2_chrom_int_0.geometry} material={materials.chrom_int} />
          <mesh geometry={nodes.dynamic_door_2_dynamics_0.geometry} material={materials.dynamics} />
          <mesh geometry={nodes.body_all_Ext_3_body_main_0.geometry} material={materials.body_main} />
          <mesh geometry={nodes.reflectors__door_2_reflectors_0.geometry} material={materials.reflectors} />
          <mesh geometry={nodes.carbon__door_2_carbon_int_0.geometry} material={materials.carbon_int} />
          <mesh geometry={nodes.logo_door_2_LOGO1_0.geometry} material={materials.LOGO1} />
          <mesh geometry={nodes.screw_door_2_black_metal_0.geometry} material={materials.black_metal} />
          <mesh geometry={nodes.leather_door_2_leather_int_0.geometry} material={materials.leather_int} />
          <mesh geometry={nodes.leather_door_2_leather_seam_0.geometry} material={materials.leather_seam} />
          <mesh geometry={nodes.plastic_exterior__door_2_bl_pl_M_ext_0.geometry} material={materials.bl_pl_M_ext} />
          <mesh geometry={nodes.reisin__door_2_reisin_0.geometry} material={materials.reisin} />
          <mesh geometry={nodes.window_door_2_windows_0.geometry} material={materials.windows} />
          <mesh geometry={nodes.window_door_2_windows_edge_0.geometry} material={materials.windows_edge} />
          <mesh geometry={nodes.mirror_cover_door_2_monitor_0.geometry} material={materials.monitor} />
        </group>
        <mesh geometry={nodes.reisin_all_reisin_0.geometry} material={materials.reisin} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.plastic_exterior_bl_pl_M_ext_0.geometry} material={materials.bl_pl_M_ext} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.black_metal_all_black_metal_0.geometry} material={materials.black_metal} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.mirror_middle_Mirror_0.geometry} material={materials.Mirror} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.carbon_all_carbon_int_0.geometry} material={materials.carbon_int} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.body_all_body_main_0.geometry} material={materials.body_main} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.lights_pattern_all_headlights_pattern_0.geometry} material={materials.headlights_pattern} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.window_black_transparent_windows_dots_0.geometry} material={materials.windows_dots} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.brakes_all_brakes_0.geometry} material={materials.brakes} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.number_plate_number_plate1_0.geometry} material={materials.number_plate1} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.monitors_seconds_monitor_0.geometry} material={materials.monitor} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.reflectors_all_reflectors_0.geometry} material={materials.reflectors} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.red_light_back_red_light_main_0.geometry} material={materials.red_light_main} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.service_black_invisible_all_0.geometry} material={materials.invisible_all} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.glossy_plastic_bl_pl__GL_int_ext_0.geometry} material={materials.bl_pl__GL_int_ext} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.chrome_int_chrom_int_0.geometry} material={materials.chrom_int} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.discs_Discs_0.geometry} material={materials.Discs} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.headlights_flash_lights_0.geometry} material={materials.lights} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.pipes_pipes_chrom_0.geometry} material={materials.pipes_chrom} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.steering_wheel_signs_pl_leather_int_0.geometry} material={materials.pl_leather_int} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.plast_leather_all_pl_leather_int_0.geometry} material={materials.pl_leather_int} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.dynamics_all_dynamics_0.geometry} material={materials.dynamics} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.trans_covers_lights_0.geometry} material={materials.lights} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.upholstery_all_upholstery_0.geometry} material={materials.upholstery} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.AO_tire_main_tires_0.geometry} material={materials.tires} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.logo_all_LOGO1_0.geometry} material={materials.LOGO1} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.belts_all_belts_0.geometry} material={materials.belts} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.rugs_all_rug_interior_0.geometry} material={materials.rug_interior} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.metal_parts_rim_chrome_0.geometry} material={materials.rim_chrome} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/porsche.glb')
